### ISSUE TITLE
OLDKEY

### ISSUE THREAD

**Issue by TranTrongSang** [parthgupta1208/PresentSmart#2]
Can you show me what is the meaning of the word "OLDKEY" in the Installation part:
OLDKEY = "user-value"
I have no idea about this.
![Problem](https://github.com/user-attachments/assets/63cc75f8-e4c3-4ba4-a9be-e1aa7ae6cca8)

**Comment by parthgupta1208** [comment]
Dont worry about it, We don't use it anywhere. Thanks for the reminder, I'll remove it from the README, my bad.
